a: P1_fifo.c
	gcc P1_fifo.c -o a

b: P2_fifo.c
	gcc P2_fifo.c -o b

c: P1_msgq.c
	gcc P1_msgq.c -o c

d: P2_msgq.c
	gcc P2_msgq.c -o d

e: P1_sockets.c
	gcc P1_sockets.c -o e

f: P2_sockets.c
	gcc P2_sockets.c -o f