a: bonus_q1.c
	gcc bonus_q1.c -o a -lpthread

Q1.o: bonus_q1.c
	gcc bonus_q1.c -c -o Q1.o

Q1.asm: bonus_q1.c
	gcc -S bonus_q1.c -o Q1.asm

c: bonus_q3.c
	gcc bonus_q3.c -o c -lpthread

Q3.o: bonus_q3.c
	gcc bonus_q3.c -c -o Q3.o

Q3.asm: bonus_q3.c
	gcc -S bonus_q3.c -o Q3.asm