Q1_a_exe: main.c
	gcc main.c -o Q1_a_exe

Q1_a.o: main.c
	gcc main.c -c -o Q1_a.o

Q1_a.asm: main.c
	gcc -S main.c -o Q1_a.asm

Q1_b_exe: Question1b.c
	gcc Question1b.c -o Q1_b_exe -lpthread

Q1_b.o: Question1b.c
	gcc Question1b.c -c -o Q1_b.o

Q1_b.asm: Question1b.c
	gcc -S Question1b.c -o Q1_b.asm


